backend:
  name: github
  repo: lntuandat/wedHue
  branch: master
  auth_scope: repo
  app_id: "Ov23li6DYEU120Wr0rSn"
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: Content Manager

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "index"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "images"
    label: "Images"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "styles"
    label: "Styles"
    files:
      - label: "Main Stylesheet"
        name: "styles"
        file: "static/styles.css"
        fields:
          - { label: "CSS Content", name: "content", widget: "code", code_mode: "css" }
