backend:
  name: github
  repo: lntuandat/wedHue
  branch: master
  auth_scope: repo
  app_id: Ov23li6DYEU120Wr0rSn
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: Content Manager


media_folder: "images" # Thư mục chứa hình ảnh upload bởi Decap CMS
public_folder: "/images" # Đường dẫn công khai cho các hình ảnh

collections:
  - name: "pages" # Tên bộ sưu tập
    label: "Pages" # Nhãn hiển thị
    files:
      - label: "index" # Trang chủ
        name: "index"
        file: "index.html" # Đường dẫn tới tệp
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "images"
    label: "Images"
    folder: "images" # Thư mục chứa hình ảnh
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "styles"
    label: "Styles"
    files:
      - label: "Main Stylesheet"
        name: "styles"
        file: "static/styles.css"
        fields:
          - { label: "CSS Content", name: "content", widget: "code", code_mode: "css" }
